Fix issue with tagbar changing the global scrolloff value.
preservim/tagbar pull request #694
Opened 2020-10-29 16:36 UTC by raven42

Closes #693

Tagbar is overwriting the global scrolloff value which can affect other windows. Change the behavior so it does a setlocal instead when needed so this only impacts the tagbar window

2020-10-29 17:32 UTC, alerque requested changes

2020-10-29 17:32 UTC, alerque commented on autoload/tagbar.vim
> +        execute 'setlocal scrolloff=' . scrolloff_save
```suggestion
        let &l:scrolloff = scrolloff_save
```
I see why execute gets the job don, but I'm not a fan of composing commands as strings and passing them to be evaled when there is a direct method available.

2020-10-29 18:21 UTC, alerque approved these changes

2020-10-29 18:21 UTC, merged

2020-10-30 15:19 UTC, Shane-XB-Qian commented
looks this change did not work well, e.g `set scrolloff=0` at line#2126
did not dig code detail, just chk looks it seems like that .. and influenced others windows if set value to this option.

2020-10-30 15:30 UTC, raven42 commented
@Shane-XB-Qian can you please elaborate? This change was to update tagbar to use `setlocal` instead of `set` so it is not changing a global setting.

2020-10-30 16:12 UTC, Shane-XB-Qian commented
sorry, i have no time to dig detail, but for now obviously not correct:
you can e.g start vim with `let g:tagbar_scrolloff=16` and `set so=10`, you can see globally value had been influenced.

2020-10-30 16:44 UTC, raven42 commented
@Shane-XB-Qian I think you must have not pulled in this fix. This fix specifically fixes the issue you are referring to. The `g:tagbar_scrolloff` field was introduced in #692. But this fix was to correct the behavior which already existed in the tagbar code where it was setting the global `scrolloff`. Please make sure you pull in the latest and try again. I tested with the values you specified and when I issue a `echo &scrolloff` in the tagbar window, I see 16, and then without changing anything if I issue that in another window, I see a value of 10.

2020-10-30 19:01 UTC, alerque commented
> What this _let &l:scrolloff = scrolloff_save_ for?

That sets the *buffer local* scroll off value to the previously saved value.

> And check line#2126 there is _set scrolloff=0_ too.

This is a second instance of the problem we were fixing. This PR fixed one instance, that is a different one.

> I felt those code original author was trying to save _&so_ value, then _zt_, then recover.

The original code was saving a value, setting it to something else, doing the action, then restoring the value. The problem was the set it was doing was a global set instead of a local one, then restored it also by doing a global set instead of local.

@raven42 The instance you fixed is in `s:RenderContent()`, the one tripping up @Shane-XB-Qian is another instance of the same kind of error in `s:RenderKeepView()` that we didn't touch at all.

2020-10-30 19:03 UTC, raven42 commented
Honestly I'm not sure the purpose of this little block of code. I found this while looking at another issue and thought I'd fix it so we aren't changing the global scrolloff value.

2020-10-30 20:29 UTC, raven42 commented
I've pushed up another PR (#697) that will address the other instance of this bug. I've also looked for any other instances where the scrolloff is being adjusted, and this looks like the only other place.